# Generated by Django 3.1.5 on 2021-01-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_host', models.CharField(max_length=15)),
                ('h_ip', models.CharField(max_length=15)),
            ],
        ),
    ]
