# Generated by Django 3.1.5 on 2021-01-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostgenapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='host',
            new_name='hosts',
        ),
    ]
